### ISSUE TITLE
Exception thrown when taxonomy is empty

### ISSUE THREAD

**Issue by xdizzy12** [jadwigo/TaxonomyList#26]
When I have a contenttype item with a taxonomy, it will crash the page when I pass parameters to the twig `taxonomylist` function. 

I'm getting the following fatal error:
```
An exception has been thrown during the rendering of a template ("Parameter "slug" for route "taxonomylink" must match "[^/]++" ("" given) to generate a corresponding URL.") in "partials/_bar-articles.twig" at line 2.
```

It seems the function doesn't understand content items not having an assigned taxonomy, and I can't find a way to make taxonomy a required field or give it a default value.

**Comment by jadwigo** [comment]
Can you give some more information.

What is the contenttypes.yml and the taxonomy.yml for those contenttypes, and what warameters are you passing to taxonomylist (in your twig template)?

---

The quick fix would be to check for empty taxonomylinks or passing a default in the template "partials/_bar-articles.twig" before invoking taxonomylist.

Checking if taxonomy exists - something along the lines of
```twig
{% if record.taxonomy.categories %}
    {% set list = taxonomylist('categories') %}
    <!-- do stuff -->
{% endif %}
```
Or checking if a slug exists before printing it.
```twig
{% set list = taxonomylist('categories') %}
<ul>
    {% for item in list if item.slug is defined %}
        <li>
            <a class="taxonomy-{{ item.slug }}" href="{{ item.link }}" title="{{ item.name }}">
                {{ item.name }}
            </a>
        </li>
    {% endfor %}
</ul>
```

**Comment by xdizzy12** [comment]
The error actually happens in the taxonomylist function itself, not on iteration or anything I (think I) am doing myself. Also the Twig error says it's the line with the taxonomylist function (and nothing else).

I am making a dictionary where content items are assigned to letters (using taxonomy). I need to print all letters which have published content items to put in a overhead menu.

```
dictionary:
    name: Dictionary
    singular_name: Dictionary
    slug: dictionary
    singular_slug: definition
    default_status: published
    fields:
        name:
            type: text
            class: large
            group: content
            required: true
        slug:
            type: slug
            uses: name
            required: true
        {some content and images}
    taxonomy: letters
    listing_template: dictionary-listing.twig
    record_template: dictionary-record.twig
```
And the taxonomy: 
```
letters:
    name: Letter
    singular_name: Letter
    slug: letters
    singular_slug: letter
    behaves_like: grouping
    listing_template: letters-listing.twig
    options: [ "a" ,"b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z" ]
```

The line which errors in twig is
```
    {% set letters = taxonomylist('letters', { 'orderby': 'name' }) %}
```
